configuration of repository

diff --git a/VoColClient/Hooks/pre-commit b/VoColClient/Hooks/pre-commit
--- a/VoColClient/Hooks/pre-commit
+++ b/VoColClient/Hooks/pre-commit
@@ -26,16 +26,24 @@
           
             echo " ${fileContent} " > tempFileCurl.ttl
 
-	    res=$(curl -X POST --data-binary @tempFileCurl.ttl http://vocol1.vagrantshare.com/client)  
+	    res=$(curl -X POST --data-binary @tempFileCurl.ttl http://mobivoc.vagrantshare.com/client)  
 
-	    if echo $res | grep -q "Error"; then
-		echo "\t\033[31mValidation Failed! ${file}\033[0m"
-		echo $res
-		pass=false
-	    else
-	       echo "\t\033[32mValidation Passed! ${file}\033[0m"
-	       echo "$res" > ${file}
-	    fi
+            if [ "$?" = "6" ] || [ "$?" = "7" ]; then 
+                echo "\t\033[31mConnection refused or service not available\033[0m";
+                echo "\t\033[31mValidation Failed! ${file}\033[0m"
+                pass=false
+            else
+
+              if echo $res | grep -q "Error"; then
+                  echo "\t\033[31mValidation Failed! ${file}\033[0m"
+                  echo $res
+                  pass=false
+              else
+                 echo "\t\033[32mValidation Passed! ${file}\033[0m"
+                 echo "$res" > ${file}
+              fi
+            
+            fi
    
             rm -f tempFileCurl.ttl
 
